// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxBUQdGOShM-eWAnZA09DbcIG6HHWbv8',
    appId: '1:482736950782:web:6a3d185f816743bba344af',
    messagingSenderId: '482736950782',
    projectId: 'venue-x-backend',
    authDomain: 'venue-x-backend.firebaseapp.com',
    storageBucket: 'venue-x-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD7EkvrbQscO7OyrmhiG1xHyO_u2V2ssM',
    appId: '1:482736950782:android:f4f08f4d6413c195a344af',
    messagingSenderId: '482736950782',
    projectId: 'venue-x-backend',
    storageBucket: 'venue-x-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBvq8ce9yai-FCYF6MGdyz1xV6B-E0JDw',
    appId: '1:482736950782:ios:cc62b06a18db7c78a344af',
    messagingSenderId: '482736950782',
    projectId: 'venue-x-backend',
    storageBucket: 'venue-x-backend.appspot.com',
    iosBundleId: 'com.example.venuex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBvq8ce9yai-FCYF6MGdyz1xV6B-E0JDw',
    appId: '1:482736950782:ios:cc62b06a18db7c78a344af',
    messagingSenderId: '482736950782',
    projectId: 'venue-x-backend',
    storageBucket: 'venue-x-backend.appspot.com',
    iosBundleId: 'com.example.venuex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANxBUQdGOShM-eWAnZA09DbcIG6HHWbv8',
    appId: '1:482736950782:web:867a44b0e15832d2a344af',
    messagingSenderId: '482736950782',
    projectId: 'venue-x-backend',
    authDomain: 'venue-x-backend.firebaseapp.com',
    storageBucket: 'venue-x-backend.appspot.com',
  );
}
